# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
archives:
- replacements:
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
- license: Apache 2.0
  formats:
  - deb
  - rpm
  bindir: /usr/libexec/oci/hooks.d/
  empty_folders:
    - /etc/oci-injector-hook
  files:
    "config/oci-injector-hook.json": "/etc/containers/oci/hooks.d/oci-injector-hook.json"
  overrides:
    rpm:
      dependencies:
      - podman
