tagFormat: ${version}
plugins:
- - "@semantic-release/commit-analyzer"
  - releaseRules:
    - type: "major"
      release: "major"
    - type: "minor"
      release: "minor"
    - type: "patch"
      release: "patch"
- "@semantic-release/changelog"
- - "@semantic-release/git"
  - assets: [ "CHANGELOG.md" ]
- "@semantic-release/release-notes-generator"
- - "@semantic-release/github"
  - assets:
    - path: dist/oci-injector-hook-${version}.x86_64.rpm
      label: oci-release-hook x86_64 RPM
