name: goreleaser-build

on:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      -
        name: Build with GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --skip-publish --rm-dist
      -
        name: Upload RPM artifact
        uses: actions/upload-artifact@v1
        with:
          name: rpm
          path: dist/*.rpm
